### ISSUE TITLE
【需求】模块热插拔

### ISSUE THREAD

**Issue by NetModular** [NetModular/NetModular#3]
是时候搞一搞了~

**Comment by iamoldli** [comment]
因为每个模块中都有自己的服务需要注入到容器，比如Repository、Service等，而微软的依赖注入设计理念是，依赖容器一旦创建，就不允许在修改，所以只能在系统启动前把所有服务注入。也就是说，在运行时无法再注入新的服务了，所以没法实现热插拔了~

**Comment by zzmzaizai** [comment]
是否可以在系统初始化时加载各个插件，通过AssemblyLoadContext检索出需要注入项。当插件安装和卸载时重启当前站点
